### ISSUE TITLE
Consider returning Text object in Translator methods instead of None

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#103]
Rather than returning `None` in the translator methods if the translation is not possible for some reason, should we instead return a Text object?

**Comment by larrybabb** [comment]
I think we should definitely do this, but we should consider whether we add an optional argument on the method(s). Something like, `"Un-translatable returned as Text" `set to FALSE by default or just modify the description of the method(s) to clearly state that it will ALWAYS return a Text object if it cannot translate the string.

I think folks will need to consider what text they would use for the `Text` form of the variant. Otherwise folks may presume that everything coming back is a meaningfully translated form of a VRSified variation.

This is a great idea and will help with clinvar project since we will be sending the variation id for stuff we know will not translate. but for stuff that we expect to translate we may want to get back `None`. I suppose we could always check the `type` of the returned object to be sure we are getting a `None` or not.

What do @theferrit32 and @tnavatar and @ahwagner think?

**Comment by ahwagner** [comment]
I fully agree with @larrybabb. Default behavior should be `None`, with a parameter to enable translation to `VT` objects.

**Comment by tnavatar** [comment]
Default as "None" works for me.

**Comment by korikuzma** [comment]
Text is being removed in VRS 2.0-alpha. I think we can close this.

**Comment by korikuzma** [comment]
Closing. We don't have Text object in draft VRS 2.0
