### ISSUE TITLE
Replace vrs models with pydantic generated models

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#194]
Use the vrs 2.0 alpha schema for this...

1. Replace pythonjsonschemaobjects tool in core by using https://github.com/koxudaxi/datamodel-code-generator/ to generate the pydantic classes which can be manually modified (for the short term).
  - use the generator to bootstrap the generation of classes and manually update and add them to vrs-python
  -  NOTE: we may be concerned about continuing to use the generator after we bootstrap for fear of having to deal with keeping the manual updates in sync.  We DO want to keep in alignment with Pydantic's approach because other tools are somewhat reliable on this and it may help with our future LinkML upgrade in the future.

**Comment by theferrit32** [comment]
Taking some notes on what needs to be done to the input/output of `datamodel-codegen`:
- jsonschema files need to use `definition` instead of `$defs`. datamodel-codegen seems to not support `$defs` which is used in recent jsonschema versions like 2020-12.
- for a union Field with a discriminator, that discriminated field needs to be a `Literal`. Like `type` on Variation subclasses.
- digestible fields from the objects in the jsonschema document need to be added to the outputted model classes

**Comment by theferrit32** [comment]
@toneillbroad

**Comment by theferrit32** [comment]
closing as completed as a work in progress in the 2-alpha branch
