### ISSUE TITLE
Update notebooks to for 2.x release

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#242]
@wesleygoar  here's how I would organize the items that need to be updated by notebook. Please edit as you go through to define the refactoring work.
- [ ] notebook 1 
    - [ ] item 1

**Comment by wesleygoar** [comment]
* [ ]  Schema.ipynb
   
   * [ ]  Locations example is broken. SimpleInterval has been removed in 2.0

**Comment by wesleygoar** [comment]
* [ ]   Operations.ipynb
   * [ ] Load data saved by Schema notebook is broken. This should be removed since the Schema notebook will be removed and then refactored into a new getting_started notebook if necessary. 
   * [ ] Everything under Computing Identifiers as objects is broken due to the Schema notebook being broken. Again I think we should consider what we want to save and create a new getting_started notebook. 
**I recommended this notebook be deleted and the purpose of the notebook be incorporated into a new getting_started notebook**

**Comment by wesleygoar** [comment]
After talking with @larrybabb, @theferrit32, & @toneillbroad we think we should have a README for the notebooks directory that briefly describes what the purpose of each notebook is and moving the notebook text from the main README into that. We could put a simple link in the main README to the notebooks.

**Comment by korikuzma** [comment]
@toneillbroad Updated notebooks.
