### ISSUE TITLE
Add support for translating inversion variants from HGVS

### ISSUE THREAD

**Issue by melissacline** [ga4gh/vrs-python#29]
The VR translator does not currently support translation of inversion variants from HGVS to VR, and throws exceptions upon encountering any.  Sample variants include:
 NC_000013.11:g.32319069_32319070inv
NC_000013.11:g.32338162_32338163inv
NC_000013.11:g.32355094_32355095inv

**Comment by reece** [comment]
@melissacline : Thanks for the issue with examples.
Would you please elaborate on how you intend to use this representation?

**Comment by reece** [comment]
My inclination is to view the notion of inversion as one or both of 1) nomenclature for humans, 2) mechanism rather than sequence result. Neither of these is in scope for VR Spec. So, our goal is to explain how to address these use cases with VR Spec, but not necessarily to implement them in VR Spec. 

There are at least two distinct strategies to implement inversions:
1. As insertion Alleles with the inverted sequence
2. As symbolic insertions

Each of these has pros and cons. Because (2) is a special case of (1), it creates a new way to represent insertion of an inverted sequence. In other words, (2) increases the ambiguity of representation.

**Comment by melissacline** [comment]
These are the three examples of inversions in our dataset.  Since these inversions are rather small (2 variants apiece), it seems arbitrary that they were labeled as inversions rather than normal indels.  It seems more plausible that the biological mechanism was an indel that by coincidence had the effect of inverting a couple bases, rather than removing a sequence and re-inserting it inverted.  With that in mind, Option 1 would serve our needs just fine.

**Comment by reece** [comment]
Great to know. I will plan implement that in the translator. Since that has no effect on the spec, that's something that I can do quickly. I'll use this issue to track implementation.

**Comment by andreasprlic** [comment]
Just to add here that some inversions can be quite big. For example this paper describes a 10Mb inversion that is related to Lynch syndrome  https://doi.org/10.1002/gcc.10094
