### ISSUE TITLE
Improve VRS ID computation performance

### ISSUE THREAD

**Issue by ehclark** [ga4gh/vrs-python#305]
This issue is intended to be the beginning of a discussion/analysis of how we might improve the VRS ID computation performance.

### Generating a Baseline
To generate baseline performance/profile data, I ran AnyVar locally and used the annotate VCF REST endpoint to process a single VCF file with 13,275 ref and alt alleles.  AnyVar used a local Postgres storage backend and a local Seqrepo instance.

AnyVar code was the main branch, commit https://github.com/biocommons/anyvar/commit/5c1f37d3f7888ffb0a5d798a81574d7a12deffd4
vrs-python code was the 2-alpha branch, commit 1a2509529becbc836c28015930dd60acc349b1df

My local workstation is a 2018 MacBook Pro with 2.6GHz i7, 32GB RAM and an SSD.  To run AnyVar and generate profiling data:
```bash
cd anyvar
source venv/3.11/bin/activate
SEQREPO_DATAPROXY_URI=seqrepo+file:///usr/local/share/seqrepo/2021-01-29
python3 -m cProfile -o cprofile_baseline.stats -m uvicorn anyvar.restapi.main:app
```

I then used https://github.com/jrfonseca/gprof2dot to convert the profile into an [SVG image](https://github.com/ga4gh/vrs-python/assets/5367470/6817241a-8508-43a2-9258-0f1919695213).

The total time to process the file was 38.7 seconds (excluding server/module startup overhead and request/response I/O).

### Analyzing the Baseline
There are two main branches in the code: generating the VRS object and then serializing the VRS object.  Generating the VRS object is approx 75% of the total processing time; serializing the remaining 25%.  

The VRS object generation appears to be pretty efficient, with the number of method calls closely correlated to the total number of alleles processed and a significant portion of the time consumed by low level file I/O operations in pysam.

Both VRS generation and serialization call into the `ga4gh_identify` method, which is called 66,375 times, or 5 times for each allele.  The methods `ga4gh_digest` and `ga4gh_serialize`, are called 146,025 times.  This indicates the methods are likely being called more times than necessary.

### Improvements
I focused on simple (or perhaps naive?) changes to eliminate serialization where it appeared to be unnecessary.  I identified two places where serialization is done when the identifier generated by the serialization is already available.  Those changes are present in the associated `performance` branch.

Running the same test again with those changes, and a small change in AnyVar to take advantage of the modified `vrs_enref` method, yielded a significant gain completing in 29.7 seconds.  [SVG of profile](https://github.com/ga4gh/vrs-python/assets/5367470/320c9431-c61a-42a2-a805-92ac08b8364c)

### And so...
In the code I observed several places where defensive copies are being made and the duplicative calls to generate identifiers would certainly eliminate risk of internal VRS object inconsistency.  So a big question is whether the changes eliminate guardrails that were put in intentionally or not.  And whether the additional assumptions made by the modifications are valid.

Would be great to hear from @reece and @korikuzma what their thoughts are on whether these improvements are worth pursuing.

**Comment by korikuzma** [comment]
@ehclark I think the changes you made are great. 

I only have concerns with the changes to`ga4gh_identify` in cases where a user provides an invalid identifier. For example:

```python
a_dict = {
    "type": "Allele",
    "location": {
        "type": "SequenceLocation",
        "sequenceReference": {
            "type": "SequenceReference",
            "refgetAccession": "ga4gh:SQ.KEO-4XBcm1cxeo_DIQ8_ofqGUkp4iZhI"
        },
        "start": 128325809,
        "end": 128325810
    },
    "state": {
        "type": "LiteralSequenceExpression",
        "sequence": "T"
    }
}

ga4gh_identify(models.Allele(**a_dict))
```

will return `'ga4gh:VA.bU3n0M2YQaV5C5ebODJYZ0GnbyCrOIHi'` . But if a user provided an invalid id such as:

```python
a_dict = {
    "id": "invalid_id",  # not even a CURIE
    "type": "Allele",
    "location": {
        "type": "SequenceLocation",
        "sequenceReference": {
            "type": "SequenceReference",
            "refgetAccession": "ga4gh:SQ.KEO-4XBcm1cxeo_DIQ8_ofqGUkp4iZhI"
        },
        "start": 128325809,
        "end": 128325810
    },
    "state": {
        "type": "LiteralSequenceExpression",
        "sequence": "T"
    }
}

ga4gh_identify(models.Allele(**a_dict))
```

the function will return `invalid_id`. These cases (I don't know how frequent this would be) are why I like forcing identifiers to be created.

**Comment by ehclark** [comment]
@korikuzma I've pushed a few commits that I think address your concern with messy inputs.  I've added a function decorator that can be used to control how the `ga4gh_identify` function determines whether to compute the identifier for calls within the established context.  The 3 options are:
- ALWAYS - always compute the identifier; this is the default (and current) behavior
- INVALID - compute the identifier if it is syntactically invalid, not present or empty
- MISSING - compute the identifier if it is not present or empty

I've added the decorator to the `VCFAnnotator.annotate()` function set to `MISSING` because the inputs to originate from the translator will always be well formed.  There may be other cases where it makes sense to add it; but VCF annotation is the place it matters right now.  The context manager could also be used from another library if that makes sense.

**Comment by korikuzma** [comment]
@ehclark These changes make sense to me. Would you like to open a PR for your changes?

**Comment by reece** [comment]
Hi @ehclark. Thanks for taking the time to collect data to help make decisions!

I haven't had my head in the code in a while, but I remember debating the speed v. correctness issue. 

At one time, `ga4gh_identify()` or `ga4gh_digest()` returned `self._id` or digest if it existed, and otherwise recomputed it. This part was messy because the model has a slot for `_id`, but the digest is what matters for the computation. In any case, the effect would then be that the identifier would be cached with the object and never recomputed.

However, I also remember debating whether this was too dangerous because objects are mutable, so it should really be accompanied by invalidation, but that's impossible without constructing a dependency tree of objects. For example, calling `ga4gh_identify` on an Allele would then call `ga4gh_identify` on the Location and perhaps cache it. Then, if someone mutated either object, the identifier should be invalidated. This would be particularly insidious if Location were updated because there's no easy way to find the original Allele that has a now-invalid cached identifier. These concerns are, I think, addressed by your intention with the enum.

I do have a much more serious concern though: Your performance branch is 81 commits behind and 119 commits ahead of main. There are a very large number of distinct features in that branch that are not in main. By proceeding down this path, you are making it essentially impossible to merge individual features. One of those features is a switch to pydantic models, which merits a much larger discussion than just sliding it in on a branch.

To be clear, I'm no longer involved in vrs-python and I don't have veto power over anything, but I have a hard time overstating how much I think that all of you should work to reconcile branches immediately. The current path is not sustainable.

On a lark, I merged main into performance, which resulted in 32 file conflicts. Aside from the design drift, there is an existing and very real question of how your work will ever get to main.

**Comment by reece** [comment]
@korikuzma just informed me that there's no intention to merge, so I guess that's not an issue.

@ehclark I apologize for forceful language. -81/+119 is too reminiscent of bad experiences in trying to merge diverged code.

**Comment by ehclark** [comment]
@reece No worries.

@korikuzma Created PR #310 to merge into 2-alpha.
