### ISSUE TITLE
Update VCF_annotator readme

### ISSUE THREAD

**Issue by wesleygoar** [ga4gh/vrs-python#325]
VCF_annotator readme needs to be updated to reflect changes made to the program.

**Comment by larrybabb** [comment]
@wesleygoar who is best suited to make these changes?

**Comment by wesleygoar** [comment]
@larrybabb I can work on this.

**Comment by wesleygoar** [comment]
@korikuzma do you think I should add these flags to the READme? 
--skip_ref                      Skip VRS computation for REF alleles.
  --require_validation            Require validation checks to pass in order
                                  to return a VRS object

**Comment by korikuzma** [comment]
@wesleygoar Yes, I think all click options should be added

**Comment by wesleygoar** [comment]
@jsstevenson please advise

**Comment by jsstevenson** [comment]
IMO, for now, it'd be best just expand the existing README but this should transition to an RTD page eventually

**Comment by wesleygoar** [comment]
@jsstevenson I am talking more about format and style for adding the options

**Comment by wesleygoar** [comment]
Can i add them just like the help function does or does it need to be prettier?

**Comment by wesleygoar** [comment]
Some of these are already explained in the doc, but those are the ones that personally I think require more explanation anyways. 
![Screenshot 2024-04-05 at 9 30 17 AM](https://github.com/ga4gh/vrs-python/assets/102165525/472df771-db06-4a7d-9e84-f5626f261858)

**Comment by jsstevenson** [comment]
Making a note about this here because I am constantly forgetting where and whether this has been done: you can make autodocs for `click` functions that look like this: 

![Screenshot 2024-04-05 at 9 29 43 AM](https://github.com/ga4gh/vrs-python/assets/12942397/b4ab9a3f-d649-4e2e-bc5b-aafc7bcd7cab)

This is implemented on the `interface-updates-epic` branch in the gene normalizer: https://raw.githubusercontent.com/cancervariants/gene-normalization/interface-updates-epic/docs/source/managing_data/loading_and_updating_data.rst
