### ISSUE TITLE
Jupyter Notebooks in the Cloud

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#93]
Allow users to run the jupyter notebooks without having to clone the repo and install SeqRepo + UTA. @ahwagner suggests using [Binder](https://mybinder.org/). This will allow users to easily play around with vrs-python's functionality. 

Prerequisites:
- [x] [Deploy SeqRepo Rest API ](https://github.com/GenomicMedLab/seqrepo-rest-service/issues/1)
~~- [ ] Deploy UTA using AWS RDS instance~~
     ~~- We will create a public `anonymous` user~~

**Comment by korikuzma** [comment]
Update for SeqRepo Rest API:
    - [Public API](https://services.genomicmedlab.org/seqrepo/1/ui/)
    - [GitHub Repo](https://github.com/GenomicMedLab/seqrepo-rest-service)

**Comment by reece** [comment]
Is there a reason you don't want to use the default RDS public instance? It's plenty fast and Invitae's paying for it!

**Comment by korikuzma** [comment]
@reece mybinder only allows [these](https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L49) ports outbound

**Comment by ahwagner** [comment]
My understanding of what we are trying to do re: UTA is to build an API that can retrieve data from a UTA instance over HTTP(S), as direct connections over the postgresql default port are commonly firewalled (true here at NCH, as well as at mybinder.org as @korikuzma pointed out).

I think the intention here is to create such an API hosted by NCH, which points to an internal RDS instance (currently necessary due to NCH firewall restrictions). I agree it would be great if we could leverage the Invitae RDS for this purpose, especially once issues around [versioned Ensembl transcripts](https://github.com/biocommons/uta/issues/233) and update frequency are addressed.
